[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "default-src 'self'; base-uri 'self'; connect-src 'self' https://www.youtube.com; font-src https://s3.amazonaws.com; form-action 'self'; frame-src https://www.youtube.com; img-src 'self' https://s3.amazonaws.com; media-src https://s3.amazonaws.com https://www.youtube.com" 
    
    Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none';fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none';picture-in-picture 'none'; speaker 'self'; sync-xhr 'none'; usb 'none'; vibrate 'none'; vr 'none'"

    Referrer-Policy = "no-referrer-when-downgrade"

    X-Frame-Options = "SAMEORIGIN"

    X-Content-Type-Options = "nosniff"